/* COPYRIGHT (C) HARRY CLARK 2024 */

/* MOTOROLA 68000 ASSEMBLER */

/* THIS FILE PERTAINS MORESO TOWARDS MODULARISATION OF COMPONENTS */
/* OF BEING ABLE TO REFER TO AND MAKE SPECIFIC FUNCTIONS ABOUT */
/* THE MACRO HANDLING SCHEME */

/* THESE FUNCTIONS WILL DICTATE THE PARSING AND LEXER NOTATION */
/* USED THROUGHOUT THE PROGRAM */

/* NESTED INCLUDES */

#include "assemble.h"
#include "common.h"
#include "disasm.h"

/* SYSTEM INCLUDES */

#include <stdio.h>
#include <stdlib.h>

/* TERMINATE THE MACRO BASED ON THEIR RESPECTIVE EXPRESSION */
/* THIS IS ASSUMING THAT THERE IS WHITESPACE BETWEEN THE MACRO BEING ENDED */

/* HOWEVER, IF THERE IS A REPEAT DIRECTIVE, WE CONTINUE THE COROUTINE */
/* BEFORE RECURSING OUT OF THE MACRO TO FREE UP DESIGNATED MEMORY */

STATIC
void MACRO_TERMINATE(FILE_SEMANTIC* SEMANTIC)
{
    char SYMBOL;
    FILE_MODE MODE;
    SEMANTIC->MODE = MODE_NORMAL;

    /* IF THERE IS NO SYMBOL ENTRY */
    /* CREATE INITIALISE ONE UNDER THE ASSUMPTION OF */
    /* A NODE-BASED SYSTEM */

    /* THIS GOVERNS WHERE THE SYMBOL IS AS WELL AS */
    /* IT'S LENGTH AND ANY OTHER PREREQUISITIES THAT SHARE THAT SYMBOL */

    if(SEMANTIC->MNEMONIC != NULL)
    {
        if(SYMBOL != NULL)
        {
            /* CREATE A VOID STATIC CAST FOR EACH ITERATION OF THE SYMBOL MNEMOMIC */
            /* THIS IS SO THAT WE ARE ABLE TO READ AND POINTER TOWARDS EACH RESPECTIVE */
            /* INSTANCE IN THIS NODE-BASED SYSTEM */

            NODE_ENTRY* SYMBOL = (void*)(SEMANTIC, SEMANTIC->MNEMONIC, strlen(SEMANTIC->MNEMONIC));
        }
    }
}